name: Test

on: [ push ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        DB_PASSWORD: root
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

